### ISSUE TITLE
read-topic failing on large partitions

### ISSUE THREAD

**Issue by merlijn-sebrechts** [juju-solutions/layer-apache-kafka#7]
When partitions are too large, read-topic fails. This is because the maximum amount of characters for a command is reached. Is it possible to put the result of this in a file and use that to populate the action response?

```
Traceback (most recent call last):
  File "actions/read-topic", line 36, in <module>
    hookenv.action_set({'output': output})
  File "/usr/local/lib/python2.7/dist-packages/charmhelpers/core/hookenv.py", line 615, in action_set
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
```

**Comment by ktsakalozos** [comment]
Although this might be part of a larger issue. We added a ticket in our backlog to see how we can work around this problem for now.

Thank you for reporting this.
